export const REGISTER_CATEGORIES= 'REGISTER_CATEGORIES';
export const URL_SEARCH = process.env.REACT_APP_URL_SEARCH;
export const URL_DETAIL_PRODUCT = process.env.REACT_APP_URL_DETAIL_PRODUCT;
export const RESULTS_NUMBER = process.env.REACT_APP_RESULTS_NUMBER;
