export const REGISTRAR_CATEGORIAS= 'REGISTRAR_CATEGORIAS';
export const URL_BUSQUEDA = process.env.REACT_APP_URL_BUSQUEDA;
export const URL_DETALLE_PRODUCTO = process.env.REACT_APP_URL_DETALLE_PRODUCTO;
export const NUMERO_RESULTADOS = process.env.REACT_APP_NUMERO_RESULTADOS;
